# Generated by Django 5.0.4 on 2024-04-18 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistemas', '0002_alter_customuser_email_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
    ]
