# Generated by Django 5.0.4 on 2024-04-18 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistemas', '0004_failedloginattempt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='failedloginattempt',
            options={'verbose_name': 'Registro de intentos fallidos de inicio de sesion', 'verbose_name_plural': 'Registros de intentos fallidos de inicio de sesion'},
        ),
    ]
