# Generated by Django 5.0.4 on 2024-04-18 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemas', '0005_alter_failedloginattempt_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, verbose_name='Usuario')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('risk_level', models.CharField(choices=[('low', 'Riesgo bajo'), ('medium', 'Riesgo medio'), ('high', 'Riesgo alto')])),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='failedloginattempt',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha'),
        ),
    ]
