# Generated by Django 5.0.4 on 2024-04-19 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistemas', '0006_risklog_alter_failedloginattempt_timestamp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='risklog',
            options={'verbose_name': 'Log de riesgo', 'verbose_name_plural': 'Logs de riesgos'},
        ),
    ]
