# Generated by Django 5.0.4 on 2024-04-19 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemas', '0007_alter_risklog_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='risklog',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pendiente'), ('Assigned', 'Asignado'), ('Resuelto', 'Reasignado')], default='unassigned', max_length=10, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='risklog',
            name='risk_level',
            field=models.CharField(choices=[('low', 'Riesgo bajo'), ('medium', 'Riesgo medio'), ('high', 'Riesgo alto')], verbose_name='Nivel de riesgo'),
        ),
    ]
