# Generated by Django 5.0.4 on 2024-04-20 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemas', '0008_risklog_status_alter_risklog_risk_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('line_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=12)),
                ('level', models.CharField(max_length=255)),
                ('process', models.CharField(max_length=255)),
                ('component', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('event_id', models.CharField(max_length=50)),
                ('event_template', models.TextField()),
            ],
        ),
    ]
